name: find merged branches

#브랜치를 삭제하거나 수정할 수 있는 권한 부여
permissions:
  contents: write
  
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
  # schedule:
  #   - cron: "0 0 * * *"   
jobs:
  find-merged-branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
     # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Display merged branch
        id: merged-branch
        run: echo "TARGET_BRANCH=${{github.event.pull_request.head.ref}}" >> $GITHUB_ENV
      - name: delete merged head branch
        run: |
            echo "Deleting branch: $TARGET_BRANCH"
            git push origin --delete $TARGET_BRANCH || echo "Failed to delete branch $TARGET_BRANCH"
